package com.singlestore.adapter.singlestore.wizard;

import com.informatica.tools.adapters.ui.appsdk.wizard.NewDefaultAppDataObjectWizard;

public class SingleStoreDataObjectWizard extends NewDefaultAppDataObjectWizard  {
    	/* 
    	 * Get adapter id  
    	 *************************************
    	 * AUTOGENERATED CODE : DO NOT CHANGE
    	 */
    	@Override
    	protected String getAdapterId() {
    		return "com.singlestore.adapter.singlestore";
    	}

}